Индивид задание 2.75
LilSneezer/untitled pull request #10
Opened 2023-03-29 14:56 UTC by LilSneezer

2023-04-01 17:21 UTC, Separador requested changes

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Simulation.java
> +        } else {
Тут можно не делать ветку else, просто вынести код из нее сразу после if'a. Логика такая, что если `args.length != 0`, то программа продолжает выполняться.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/Customer.java
> +    public String printPurchases(ArrayList<Fruit> purchases) {
Метод не должен принимать другой список, он должен работать с внутренним объектом.
И он не должен ничего возвращать.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/Customer.java
> +    public abstract ArrayList<Fruit> takeFruits(ArrayList<Fruit> purchases);
Метод должен на вход получать Cargo и работать с ним. Также ничего не должен  возвращать.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/FreshCustomer.java
> +    public ArrayList<Fruit> takeFruits(ArrayList<Fruit> purchases) {
Смотри комментарий к методу в классе `Customer`.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/FreshCustomer.java
> +//                purchases = cargo.removeFruit(fruit);
Почему закомментировал? В этом методе ты получаешь cargo и удаляешь из него фрукты.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/UniqueCustomer.java
> +//                purchases = cargo.removeFruit(purchases.get(i));
Почему закомментировал? В этом методе ты получаешь cargo и удаляешь из него фрукты.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/UniqueCustomer.java
> +    public ArrayList<Fruit> takeFruits(ArrayList<Fruit> purchases) {
Смотри комментарий к методу в классе Customer.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Fruit.java
> +    public abstract boolean isFresh();
Этот метод можешь не делать абстрактным, а прямо тут добавить реализацию, тк она везде одинаковая.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Fruit.java
> +    public abstract boolean equals(Object obj);
Этот метод можешь не делать абстрактным, а прямо тут добавить реализацию, тк она везде одинаковая.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Fruit.java
> +    public abstract int hashCode();
Этот метод можешь не делать абстрактным, а прямо тут добавить реализацию, тк она везде одинаковая.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Orange.java
> +        return obj != null && obj.getClass() == this.getClass();
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Orange.java
> +        return 0;
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Apple.java
> +        return obj != null && obj.getClass() == this.getClass();
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Apple.java
> +        return 0;
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Pineapple.java
> +        return obj != null && obj.getClass() == this.getClass();
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Pineapple.java
> +        return 0;
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Fruit.java
> +    }
Не надо так делать. Лучше перенеси в конструктор, где не передается параметр `freshness`.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Banana.java
> +        return obj != null && obj.getClass() == this.getClass();
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Banana.java
> +        return 0;
Реализация метода неверная, не учитываются значения параметров объекта.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Simulation.java
> +                System.out.println("Оставшийся груз: \n" + fruitBase.takeOrder(arr.split(" ")));
Тебе не надо это делать, чтобы узнать сколько в `cargo` осталось фруктов. Метод `takeFruit` у покупателя изменяет состав cargo,  а тут ты  печатаешь сам `cargo`. Тем более у тебя в классе `Cargo` реализован `toString`.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Simulation.java
> +                }
Это тут не надо, смотри комментарий к методу `takeFruits` у покупателя.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Cargo.java
> +    public ArrayList<Fruit> removeFruit(Fruit fruitName) {
Метод не должен возвращать список, оставшихся объектов. По описанию он возвращает фрукт, который из него удалили.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Cargo.java
> +            System.exit(0);
А зачем ты завершаешь программу? Тебе просто надо выйти из функции.

2023-04-01 17:21 UTC, Separador commented on src/test/java/task2_66/com/customers/Customer.java
> +    Cargo cargo = new Cargo();
А зачем он здесь?

2023-04-10 16:58 UTC, LilSneezer commented
исправил

2023-04-13 10:05 UTC, Separador requested changes

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Fruit.java
> +                (Objects.equals(this.price, fruitObj.price));
Забыл про сравнение freshness.

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Fruit.java
> +        return result;
Забыл про freshness

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/FruitBase.java
> +public class FruitBase implements Serializable {
FruitBase не нужно сериализовать.

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/customers/FreshCustomer.java
> +                cargo.removeFruit(cargo.getFruits().get(i));
Есть проблема с одновременным проходом по списку и удалением элементов из этого же списка. После удаления изменяется размер и индекс указывает на другой элемент. В итоге у тебя пропускаются подходящие элементы. Это можно решить, например, разделив на два цикла - в первом ты добавляешь найденный элемент к себе, а вторым - удаляешь.

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/customers/UniqueCustomer.java
> +                cargo.removeFruit(cargo.getFruits().get(i));
Есть проблема с удалением, см. описание у FreshCustomer

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/FruitBase.java
> +        FileOutputStream fileOutputStream = new FileOutputStream("/Users/andrey/Desktop/сериализация/fruitCatalog.ser");
Не надо указаывать путь, тк этого пути может не быть. Оставь просто название файла, тогда он будет сохраняться в корень проекта.

2023-04-13 10:05 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/FruitBase.java
> +        FileInputStream fileInputStream = new FileInputStream("/Users/andrey/Desktop/сериализация/fruitCatalog.ser");
Поправь путь аналогично exportCatalogue.

2023-04-19 20:49 UTC, Separador approved these changes

2023-04-20 18:56 UTC, merged