Сделал индивид. задание 2.66
LilSneezer/untitled pull request #9
Opened 2023-03-12 13:27 UTC by LilSneezer

2023-03-12 18:30 UTC, Separador requested changes

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/fruits/Apple.java
> +        this.name = name;
Если вызываешь родительский конструктор для установки значений, то уже нет  необходимости повторно устанавливать эти же значения в дочернем конструкторе. Лучше убери, аналогично в других фруктах.

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/FruitCatalogue.java
> +                foundFruit = fruit[i];
Если ты нашел нужный фрукт, то уже не нужно продолжать проход по каталогу. Добавь выход из цикла.

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Cargo.java
> +        BigDecimal commonPrice = new BigDecimal("0");
У `BigDecimal` есть специальная константа `BigDecimal.ZERO`.

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Cargo.java
> +    public double getWeight(ArrayList<Fruit> fruit) {
Метод не должен принимать список фруктов в качестве аргумента, тк он должен считать вес объектов, которые находятся в списке в текущем объекте.

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Cargo.java
> +    public BigDecimal getPrice(ArrayList<Fruit> fruit) {
Метод не должен принимать список фруктов в качестве аргумента, тк он должен считать стоимость объектов, которые находятся в списке в текущем объекте.

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/Cargo.java
> +    public ArrayList<Fruit> getFruit() {
Этот объект не нужен, тк в данной задаче список фруктов предназначен только для внутреннего использования. А внешние классы могут получить только информацию о весе и стоимости.

2023-03-12 18:30 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/FruitBase.java
> +        return "Общий вес: " + commonWeight + "\n" + "Общая стоимость: " + commonPrice;
Вынеси вывод в `main`. Также можешь в класс `Cargo` добавить `toString`, чтобы сделать проще вывод информации.

2023-03-12 19:02 UTC, Separador requested changes
Добавил замечания по  файлам.

2023-03-12 22:29 UTC, Separador requested changes
Коммент для закрытия ревью

2023-03-13 16:31 UTC, LilSneezer commented
Поправил замечания

2023-03-13 17:11 UTC, Separador requested changes
Добавил комментарий к коду. Еще в `main` надо добавить обработку пустого `args`: если не передано аргументов, то надо завершить программу.

2023-03-13 17:11 UTC, Separador commented on src/test/java/task2_66/com/fruitbase/FruitBase.java
>      public String takeOrder(String[] fruitsFromOrder) {
`takeOrder` должен возвращать Cargo

2023-03-17 20:48 UTC, merged